export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";

// export const GET_POST_DETAILS = "GET_POST_DETAILS";
// export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
// export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL";