export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";

// export const GET_POST_DETAILS = "GET_POST_DETAILS";
// export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
// export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";

export const PUT_ITEM = "PUT_ITEM";
export const PUT_ITEM_SUCCESS = "PUT_ITEM_SUCCESS";
export const PUT_ITEM_FAIL = "PUT_ITEM_FAIL";

export const GET_FAVORITE_ITEMS = "GET_ITEMS";
export const GET_FAVORITE_ITEM_SUCCESS = "GET_FAVORITE_ITEM_SUCCESS";
export const GET_FAVORITE_ITEM_FAIL = "GET_FAVORITE_ITEM_FAIL";

export const TOGGLE_FAVORITE_ITEM = "TOGGLE_FAVORITE_ITEM";
export const TOGGLE_FAVORITE_ITEM_SUCCESS = "TOGGLE_FAVORITE_ITEM_SUCCESS";
export const TOGGLE_FAVORITE_ITEM_FAIL = "TOGGLE_FAVORITE_ITEM_FAIL";
