export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";

export const POST_ITEMS = "POST_ITEMS";
export const POST_ITEM_SUCCESS = "POST_ITEM_SUCCESS";
export const POST_ITEM_FAIL = "POST_ITEM_FAIL";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";

export const PUT_ITEM = "PUT_ITEM";
export const PUT_ITEM_SUCCESS = "PUT_ITEM_SUCCESS";
export const PUT_ITEM_FAIL = "PUT_ITEM_FAIL";

export const GET_FAVORITE_ITEMS = "GET_ITEMS";
export const GET_FAVORITE_ITEM_SUCCESS = "GET_FAVORITE_ITEM_SUCCESS";
export const GET_FAVORITE_ITEM_FAIL = "GET_FAVORITE_ITEM_FAIL";
